### ISSUE TITLE
Public Instance: Duplicate Torrents being added in RealDebrid

### ISSUE THREAD

**Issue by jishnurk** [mhdzumair/MediaFusion#243] opened 2024-07-20 13:34 UTC
Opening a stream leads to duplicate torrents (same torrent) being added in RealDebrid.

Issue occurs only in Public/Elfhosted instance.

**Comment by jishnurk** [comment] 2024-07-20 13:35
@mhdzumair Is it possible for you to check the logs? Since it is not happening in local instance, I am unable to debug.

**Comment by mhdzumair** [comment] 2024-07-20 13:40
This issue was handled sometimes back with caching and locking the `streaming_provider_endpoint` function. are you facing this issue?

**Comment by jishnurk** [comment] 2024-07-20 13:43
Yes, I am. Attached a screenshot:

![Screenshot 2024-07-20 153333](https://github.com/user-attachments/assets/a4e8f044-8cab-4958-9344-f2b7971823c8)

**Comment by mhdzumair** [comment] 2024-07-20 13:58
Stremio sending two request initially, 
1. From the player.
2. From Stremio server to calculate video OpenSubtitle hash. 

Both request are firing nearly simultaneously. We need to ensure the redis locking is working correctly. Apart from that, Public Elfhosted has 10 pods, so both request might be handling in two different pods simultaneously. However, we use 1 single redis. 

@coderabbitai would you chime into find a solution or fixes?  The streaming provider codes are in streaming_providers/routes.py

**Comment by mhdzumair** [comment] 2024-09-18 04:39
The issue has been identified and resolved in the latest code. So the issue is due to the info hash stored in the db is in caps letters for prowlarr data. Then It's failing to match the info hash, therefor it's adding multiple times. 

we need to do the cleanup on torrent data in elfhosted. until then ill keep open this.

**Comment by mhdzumair** [comment] 2024-09-19 12:25
The release is probably set for this weekend. All the changes on my wishlist are almost complete, though a few more tasks need to be finished on the live TV side. As for the poster, it’s stored in Redis, so cleaning up Redis will generate new posters.

Additionally, I announced the Alldebrid voucher giveaway for contributors. Please post your email, so I can send you the voucher code as a thank you for your excellent contributions.

**Closed** 2024-10-05 21:08 UTC

**Comment by jishnurk** [comment] 2024-12-06 23:49
@mhdzumair I am observing this issue again... :(
